### PR TITLE
[fixes] Fixed some typos and improved overrall code structure

### PR DESCRIPTION
**Pull request by Zffu**
Changelog:
- Fixed typos located in the docs of the generatePassword function
- Moved the arrays instances into the "arrays" object for better code structure and to avoid to have to create the array instance at each function call which could result in a performance loss.

### CODE REVIEW

**Comment by Caesarovich** [comment]
Is this Devin at work ? 😄

**Comment by Zffu** [comment]
nope, just a random dude that was at tumo a long time ago.

**Comment by Caesarovich** [comment]
Nice, which Center have you been to ? @Zffu

**Comment by Zffu** [comment]
The Lyon one

**Comment by Caesarovich** [comment]
Ah mais je dois te connaître alors, tu t'appelles comment ? @Zffu

**Comment by Zffu** [comment]
je peut dire mon prénom c'est Eliott

**Pull request merged**
